channels:
- defaults
- conda-forge
dependencies:
- pip=19.3.1
- ipykernel=5.1.3
- ipython=7.9.0
- jupyterlab=1.2.0
- matplotlib=3.1.1
- numpy=1.17.3
- xarray=0.14.0
- pip:
  - karabo_data==0.7.0
  - awscli==1.16.272
